custom_user/cust_user/cust_user/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from user.views import (login_view,
                        register_view,
                        logout_view,
                        generate_token,
                        home_view,
                        )
from myapp.views import auto_suggest, world_detail

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_view, name='home'),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^details/', world_detail, name='details'),
    url(r'^ajax/get_otp/$', generate_token, name='generate_token'),
    url(r'^ajax/auto_suggest/$', auto_suggest, name='auto_suggest'),
    url(r'^api/user/', include("user.api.urls", namespace='user-api')),

]

custom_user/cust_user/user/forms.py
from django import forms
from django.contrib.auth import (
    get_user_model
)
from django.db.models import Q

User = get_user_model()


class UserLoginForm(forms.Form):
    email = forms.EmailField()
    phone_number = forms.CharField(label="10 Digit Registered Phone Number (Include country code)")
    number_or_email = forms.CharField(label='OTP Phone Number or Email')
    token = forms.CharField(label='OTP')
    # class Meta:
    #     model = User
    #     fields = [
    #         'email',
    #         'phone_number',
    #     ]
    #
    #
    # def clean(self, *args, **kwargs):
    #     email = self.cleaned_data.get("email")
    #
    #
    #     # user_qs = User.objects.filter(username=username)
    #     # if user_qs.count() == 1:
    #     #     user = user_qs.first()
    #     if email:
    #         user = authenticate(email=email)
    #         if not user:
    #             raise forms.ValidationError("This user does not exist")
    #         if not user.is_active:
    #             raise forms.ValidationError("This user is not longer active.")
    #     return super(UserLoginForm, self).clean(*args, **kwargs)


    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        phone_number = self.cleaned_data.get("phone_number")

        user = User.objects.filter(
                            Q(email=email)&
                            Q(phone_number=phone_number)
                        )
        if not user.exists():
            raise forms.ValidationError('User does not exist')

        if not user.first().is_active:
            raise forms.ValidationError('User is inactive')

        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegisterForm(forms.ModelForm):
    MALE = 'M'
    FEMALE = 'F'
    GENDER = ((MALE, 'MALE'), (FEMALE, 'FEMALE'))

    email = forms.EmailField(label='Email address')
    email2 = forms.EmailField(label='Confirm Email')
    first_name = forms.CharField(label='First Name')
    last_name = forms.CharField()
    gender = forms.ChoiceField(GENDER)
    phone_number = forms.CharField(label="10 Digit Registered Phone Number (Include country code)")
    class Meta:
        model = User
        fields = [
            'email',
            'email2',
            'first_name',
            'last_name',
            'gender',
            'phone_number'
        ]

    # def clean(self, *args, **kwargs):
    #     email = self.cleaned_data.get('email')
    #     email2 = self.cleaned_data.get('email2')
    #     if email != email2:
    #         raise forms.ValidationError("Emails must match")
    #     email_qs = User.objects.filter(email=email)
    #     if email_qs.exists():
    #         raise forms.ValidationError("This email has already been registered")

    #     return super(UserRegisterForm,self).clean(*args, **kwargs)

    def clean_email2(self):
        email = self.cleaned_data.get('email')
        email2 = self.cleaned_data.get('email2')
        if email != email2:
            raise forms.ValidationError("Emails must match")
        return email





















custom_user/cust_user/templates/base.html
<html>
<head>
<title>{% block head_title %}{% endblock head_title %}</title>
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' >

{% block style %}{% endblock style %}
{% block head_extra %} {% endblock head_extra %}
</head>
<body>



<div class='container-fluid'>
<div>
{% include 'nav.html' %}
</div>

{% block content %}{% endblock content %}

</div>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    {% block javascript %}{% endblock javascript %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


</body>
</html>

custom_user/cust_user/templates/home.html
{% extends "base.html" %}

{% block style %}
<style>

    ul {
        list-style: none;
        margin: 0;
        padding: 0;
    }

    li:hover {
        background-color: blue;
        color: white;
    }

    #suggestion-box {
        width: 200px;
        border: 1px solid black;
    }

    #search-box {
        width: 200px;
    }


</style>
{% endblock style %}


{% block javascript %}
  <script>

   $(document).ready(function(){

   var container = $("#suggestion-box");

   $("body").mouseup(function(e){
        if(!container.is(e.target) && container.has(e.target).length===0){
            container.hide();
        }
   });

	$("#search-box").keyup(function(){
		$.ajax({
		type: "GET",
		url: "ajax/auto_suggest/",
		data: {
          'keyword': $(this).val()
        },
		success: function(data){
			$("#suggestion-box").show();
			$("#suggestion-box").html(data);
		}
		});
	});
    });

    function selectKeyword(val) {
    $("#search-box").val(val);
    $("#suggestion-box").hide();
    }
  </script>

{% endblock javascript %}


{% block content %}
<div class="col-sm-6 col-sm-offset-3">
{% if request.user.is_authenticated %}
<h1>Welcome {{ request.user.get_full_name }}</h1>
{% else %}
<h1>Welcome Anonymous User</h1>
{% endif %}




<form method="GET" action="{% url 'details' %}">

<input type="search" id="search-box" name="search" placeholder="Type..." />
    <input type="submit" value="Search" class="btn btn-success">
    <div id="suggestion-box"></div>
</form>
</div>
{% endblock content %}

custom_user/cust_user/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}}



{% block javascript %}
  <script>
    $(document).ready(function(){
     $("#id_button").click(function () {
      var number_or_email = $("#id_number_or_email").val();
      $.ajax({
        type:'GET',
        url: '/ajax/get_otp/',
        data: {
          'number_or_email': number_or_email
        },
        dataType: 'json',
        success: function (data) {
         var message = data.message;
         $("#id_message").text(message);
        }
      });
    });
   });
  </script>

{% endblock javascript %}


{% block content %}
<div class="col-sm-6 col-sm-offset-3">
{% include "messages_display.html" %}
<h1>{{ title }}</h1>
<hr/>

<form method='POST' action='{url "detail"}' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
    <input type="button" id="id_button" value="GET OTP"><br/>

         {% if session_token_error %}
        <span>{{ session_token_error }}</span>
        {% endif %}

<br/>
<input type='submit' class='btn btn-default' value='{{ title }}' />
</form>
<h3 id="id_message"></h3>
{% if error %}
<h3>{{ error }}</h3>
{% endif %}
</div>
{% endblock content %}

custom_user/cust_user/templates/messages_display.html
 {% if messages %}
    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if "html_safe" in message.tags %}{{ message|safe }}
        {% else %}{{ message }}
        {% endif %}
        </li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

custom_user/cust_user/templates/nav.html
<a href="{% url 'home' %}" class="btn btn-default">Home</a>
{% if user.is_authticated %}
<a href="{% url 'logout' %}" class="btn btn-default">LogOut</a>
{% else %}
<a href="{% url 'login' %}" class="btn btn-default">Login</a>
<a href="{% url 'register' %}" class="btn btn-default">Register</a>
{% endif %}

custom_user/cust_user/templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block javascript %}
  <script>
  $(document).ready(function(){
     $("#id_button").click(function () {
      console.log("button clicked")
      var phone_number = $("#id_phone_number").val();
      $.ajax({
        url: '/ajax/get_otp/',
        data: {
          'phone_number': phone_number
        },
        dataType: 'json',
        success: function (data) {
         var phone = data.phone;
         console.log(phone);
        }
      });
    });
  });
  </script>

{% endblock javascript %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
<h1>{{title}}</h1>
<hr/>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Sign up</button>
  </form>
</div>
{% endblock %}

custom_user/cust_user/templates/world_detail.html
{% extends "base.html" %}





{% block style %}
<style>

    table, tr, td, th {
        border: 1px solid black;
        border-collapse: collapse;
    }

</style>
{% endblock style %}

{% block content %}

{% if fields %}
<br>
{% else %}
<h3>No details</h3>
{% endif %}

<table>
    <tr>
        {% for f in fields %}
            <th>{{ f.name }}</th>
        {% endfor %}
    </tr>
    {% for v in obj_list %}
    <tr>
        {% for l in v.values %}

            <td>{{ l }}</td>

        {% endfor %}
    </tr>
    {% endfor %}
</table>


{% endblock content %}